# Generated by Django 4.1.3 on 2022-12-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
